apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - namespace.yaml
  - secrets
  - jobs
  - nodes
  - storageclasses
  - rules.yaml

helmCharts:
  - name: longhorn
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: values.yaml
    version: "1.10.1"
    repo: https://charts.longhorn.io/
