apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: microblog-network-https
  namespace: kube-system
spec:
  commonName: microblog.network
  dnsNames:
    - microblog.network
    - "*.microblog.network"
  issuerRef:
    name: letsencrypt-hetzner
    kind: ClusterIssuer
  secretName: microblog-network-tls