apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: crowdsec-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0
  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi
    storageClass: longhorn-cnpg-volumes

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: crowdsec
      owner: crowdsec

  postgresql:
    parameters:
      # pgtune
      max_connections: "200"
      shared_buffers: "128MB"
      effective_cache_size: "384MB"
      maintenance_work_mem: "32MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "3932kB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "327kB"
      huge_pages: "off"
      min_wal_size: "1GB"
      max_wal_size: "4GB"

  resources:
    requests:
      memory: "512Mi"
      cpu: 100m
    limits:
      memory: "512Mi"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
