apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crowdsec

resources:
  - namespace.yaml
  - database.yaml
  - secrets.yaml

helmCharts:
  - name: crowdsec
    version: "0.20.1"
    releaseName: crowdsec
    namespace: crowdsec
    valuesFile: helm-values.yaml
    includeCRDs: true
    repo: https://crowdsecurity.github.io/helm-charts
