apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: hourly-volume-snapshot
  namespace: longhorn-system
spec:
  concurrency: 3
  cron: 0 */6 * * *
  groups:
  - default
  name: hourly-volume-snapshot
  retain: 24
  task: snapshot
