{{ if .Values.observability.metrics.podMonitor.enabled }}
{{- $context := . }}
{{- range .Values.sidekiq.workers }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "mastodon.fullname" $context }}-sidekiq-{{ .name }}
  labels:
    {{- include "mastodon.labels" $context | nindent 4 }}
    app.kubernetes.io/component: sidekiq-{{ .name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: sidekiq-{{ .name }}
  podMetricsEndpoints:
    - port: prometheus
      interval: {{ $context.Values.observability.metrics.podMonitor.interval }}
      scrapeTimeout: {{ $context.Values.observability.metrics.podMonitor.scrapeTimeout }}
      path: {{ $context.Values.observability.metrics.podMonitor.path }}
      scheme: {{ $context.Values.observability.metrics.podMonitor.scheme }}
{{ end }}
{{ end }}
