{{ if and .Values.observability.metrics.enabled .Values.observability.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "mastodon.fullname" . }}-streaming
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
    app.kubernetes.io/component: streaming
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: streaming
  podMetricsEndpoints:
    - port: {{ .Values.streaming.podMonitor.port | default "streaming" }}
      interval: {{ .Values.observability.metrics.podMonitor.interval }}
      scrapeTimeout: {{ .Values.observability.metrics.podMonitor.scrapeTimeout }}
      path: {{ .Values.observability.metrics.podMonitor.path }}
      scheme: {{ .Values.observability.metrics.podMonitor.scheme }}
{{ end }}
