apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd.yaml
  - cloudflared.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - descheduler.yaml
  - dex.yaml
  - n8n.yaml
  - elastic-operator.yaml
  - hetzner-ccm.yaml
  - haproxy-onload.yaml
  - longhorn.yaml
  - keda.yaml
  - metrics-server.yaml
  - microblog-network.yaml
  - talos-ccm.yaml
  - victoriametrics.yaml
  - vertical-pod-autoscaler.yaml
  - vpa-resources.yaml
  - toot-community.yaml
  - victorialogs.yaml
  - victoriatraces.yaml
  - robusta.yaml
  - local-path-storage.yaml
