apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toot-community
  namespace: argocd
spec:
  destination:
    namespace: toot-community
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/applications/mastodon/overlays/toot.community
    repoURL: git@github.com:toot-community/platform.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
