apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared
spec:
  gatewayClassName: traefik

  listeners:
    - protocol: HTTP
      port: 8000
      name: toot-community-http
      hostname: toot.community
      allowedRoutes:
        namespaces:
          from: All

    - protocol: HTTP
      port: 8000
      name: wildcard-toot-community-http
      hostname: "*.toot.community"
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 8443
      name: toot-community-https
      hostname: toot.community
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: toot-community-tls
      allowedRoutes:
        namespaces:
          from: All

    - protocol: HTTPS
      port: 8443
      name: wildcard-toot-community-https
      hostname: "*.toot.community"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: toot-community-tls
      allowedRoutes:
        namespaces:
          from: All

    - protocol: HTTP
      port: 8000
      name: microblog-network-http
      hostname: microblog.network
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTP
      port: 8000
      name: wildcard-microblog-network-http
      hostname: "*.microblog.network"
      allowedRoutes:
        namespaces:
          from: All

    - protocol: HTTPS
      port: 8443
      name: microblog-network-https
      hostname: microblog.network
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: microblog-network-tls
      allowedRoutes:
        namespaces:
          from: All

    - protocol: HTTPS
      port: 8443
      name: wildcard-microblog-network-https
      hostname: "*.microblog.network"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: microblog-network-tls
      allowedRoutes:
        namespaces:
          from: All
