apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      crowdsecMode: stream
      crowdsecLapiScheme: http
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
      crowdsecLapiPath: "/"
      crowdsecLapiKeyFile: /etc/traefik/secrets/crowdsec_middleware_lapi_key
      crowdsecAppsecEnabled: false
      crowdsecAppsecScheme: http
      crowdsecAppsecHost: crowdsec-appsec-service.crowdsec.svc.cluster.local:7422
      crowdsecAppsecPath: "/"
      crowdsecAppsecFailureBlock: false
      crowdsecAppsecUnreachableBlock: false
