apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-system

resources: 
  - gateway-api/certificates
  - gateway-api/shared-gateway.yaml
  - secrets.yaml
  - crowdsec-middleware.yaml

helmCharts:
  - name: traefik
    version: "38.0.1"
    releaseName: traefik
    namespace: traefik-system
    valuesFile: helm-values.yaml
    includeCRDs: true
    repo: https://traefik.github.io/charts