configuration:
  s3:
    endpoint: https://fsn1.your-objectstorage.com
    hostname: fsn1.your-objectstorage.com
    region: fsn1
    protocol: https
    timeouts:
      open: 10
      read: 10
  
  otel:
    enabled: false
    namePrefix: mastodon
    nameSeparator: /
    exporterUri: http://vt-vt-single-server.victoriatraces.svc.cluster.local:10428/insert/opentelemetry/

ingress:
  web:
    serviceNameOverride: varnish-for-app
    servicePortOverride: 80

gateway:
  enabled: true
  parentRefs:
    - name: shared
      namespace: traefik-system
  web:
    wwwRedirect:
      enabled: true