mastodon:
  allowedPrivateAddresses: "10.0.8.0/21"

redis:
  url: redis://redis-ha-haproxy:6379

s3:
  endpoint: https://fsn1.your-objectstorage.com
  hostname: fsn1.your-objectstorage.com
  region: fsn1
  protocol: https
  timeouts:
    open: 10
    read: 10

observability:
  otel:
    enabled: false
    namePrefix: mastodon
    nameSeparator: /
    exporterUri: http://vt-vt-single-server.victoriatraces.svc.cluster.local:10428/insert/opentelemetry/
  metrics:
    podMonitor:
      interval: 10s

ingress:
  web:
    enabled: false
    serviceOverride:
      name: varnish-for-app
      port: 80
  streaming:
    enabled: false

gateway:
  enabled: false
