apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-hetzner
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@toot.community
    privateKeySecretRef:
      name: letsencrypt-hetzner
    solvers:
      - dns01:
          webhook:
            solverName: hetzner
            groupName: acme.hetzner.com
            config:
              tokenSecretKeyRef:
                name: hetzner-secret
                key: token