crds:
  enabled: true
prometheus:
  enabled: true
extraEnv:
  - name: AWS_ROLE_ARN
    value: arn:aws:iam::875175157867:role/cert-manager-route53-role
  - name: AWS_WEB_IDENTITY_TOKEN_FILE
    value: /var/run/secrets/aws/token
  - name: AWS_REGION
    value: us-east-1
  - name: AWS_STS_REGIONAL_ENDPOINTS
    value: regional

volumes:
  - name: aws-web-identity-token
    projected:
      sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 3600
            path: token

volumeMounts:
  - name: aws-web-identity-token
    mountPath: /var/run/secrets/aws
    readOnly: true
