apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oidc-proxy-discovery
rules:
  - nonResourceURLs:
      - /.well-known/openid-configuration
      - /openid/v1/jwks
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-proxy-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oidc-proxy-discovery
subjects:
  - kind: ServiceAccount
    name: oidc-proxy
    namespace: oidc-issuer
