apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: vpa-resources
    version: "0.0.0"
    releaseName: vpa-resources
    valuesFile: helm-values.yaml
